name: Psychologe Lies Peters
favicon: null
layout_spectrum: 0.15724418382160366
typography_spectrum: 0.32457337947562337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9060137490741909
  lightness: 0.5355575892608613
  saturation: 0.4121888275258243
  rhythmicContrast: 0.018063057446852326
purpose: []
